"""Compatibility wrapper for backend.services.qdrant_service."""

from .services.gemini_service import generate_gemini_content
from .services.ollama_service import generate_ollama_content
from .services.qdrant_service import (
    QdrantService,
    _doc_tag_score,
    _doc_time_score,
    _enrich_with_full_article_chunks,
    _heuristic_rerank,
    _normalise_slug,
    _relaxed_fallback_search,
    _remove_accents,
    _slugify,
    _tag_variants,
    _warmup_qdrant_embedders_sync,
    embedder,
    ensure_payload_indexes,
    extract_structured_query,
    get_dense_embedder,
    get_sparse_embedder,
    get_sparse_vector,
    qdrant_client,
    rerank_documents,
    search_articles,
    warmup_qdrant_embedders,
)

__all__ = [
    "QdrantService",
    "qdrant_client",
    "embedder",
    "rerank_documents",
    "get_dense_embedder",
    "get_sparse_embedder",
    "warmup_qdrant_embedders",
    "get_sparse_vector",
    "ensure_payload_indexes",
    "extract_structured_query",
    "search_articles",
    "generate_gemini_content",
    "generate_ollama_content",
    "_enrich_with_full_article_chunks",
    "_relaxed_fallback_search",
    "_remove_accents",
    "_slugify",
    "_tag_variants",
    "_normalise_slug",
    "_doc_tag_score",
    "_doc_time_score",
    "_heuristic_rerank",
    "_warmup_qdrant_embedders_sync",
]
